- id: check-gpg-signed
  name: Check GPG signed
  description: Checks whether the most recent commit was GPG signed
  # Check if the most recent commit was signed. If not, amend it with the GPG signature
  entry: /bin/sh -c "git verify-commit HEAD || git commit -S --amend"
  language: system
  args: []
  always_run: true
  pass_filenames: false
  minimum_pre_commit_version: "2.15"
  stages:
    - post-commit
    - post-rewrite
